name: Newman Run
on:
  push:
    branches:
      - main
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create directory
        run: |
          mkdir testArtifacts

      # Configurando o ambiente
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          
      - name: Run Test
        run: newman run servRest.postman_collection.json -e servRest_test.postman_environment.json -r cli,htmlextra
        
      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: newman
